<%@ Page Title="Perdoruesit" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="user.aspx.cs" Inherits="admin_user" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="body" Runat="Server">
    <div class="container">
        <asp:GridView Width="100%" ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id_User" DataSourceID="UsersDS" PageSize="20">
            <Columns>
                <asp:BoundField DataField="Id_User" HeaderText="Id_User" InsertVisible="False" ReadOnly="True" SortExpression="Id_User" />
                <asp:BoundField DataField="Emri" HeaderText="Emri" SortExpression="Emri" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Fjalkalimi" HeaderText="Fjalkalimi" SortExpression="Fjalkalimi" />
                <asp:BoundField DataField="Datelindja" HeaderText="Datelindja" SortExpression="Datelindja" />
                <asp:CheckBoxField DataField="Administratori" HeaderText="Administratori" SortExpression="Administratori" />
            </Columns>
        </asp:GridView>
    </div>
    
    <asp:SqlDataSource ID="UsersDS" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:barcafe_onlineConnectionString2 %>" DeleteCommand="DELETE FROM [Perdorues] WHERE [Id_User] = @original_Id_User AND [Emri] = @original_Emri AND [Email] = @original_Email AND [Datelindja] = @original_Datelindja AND [Fjalkalimi] = @original_Fjalkalimi AND [Administratori] = @original_Administratori" InsertCommand="INSERT INTO [Perdorues] ([Emri], [Email], [Datelindja], [Fjalkalimi], [Administratori]) VALUES (@Emri, @Email, @Datelindja, @Fjalkalimi, @Administratori)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT [Id_User], [Emri], [Email], [Datelindja], [Fjalkalimi], [Administratori] FROM [Perdorues]" UpdateCommand="UPDATE [Perdorues] SET [Emri] = @Emri, [Email] = @Email, [Datelindja] = @Datelindja, [Fjalkalimi] = @Fjalkalimi, [Administratori] = @Administratori WHERE [Id_User] = @original_Id_User AND [Emri] = @original_Emri AND [Email] = @original_Email AND [Datelindja] = @original_Datelindja AND [Fjalkalimi] = @original_Fjalkalimi AND [Administratori] = @original_Administratori">
        <DeleteParameters>
            <asp:Parameter Name="original_Id_User" Type="Int32" />
            <asp:Parameter Name="original_Emri" Type="String" />
            <asp:Parameter Name="original_Email" Type="String" />
            <asp:Parameter DbType="Date" Name="original_Datelindja" />
            <asp:Parameter Name="original_Fjalkalimi" Type="String" />
            <asp:Parameter Name="original_Administratori" Type="Boolean" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Emri" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter DbType="Date" Name="Datelindja" />
            <asp:Parameter Name="Fjalkalimi" Type="String" />
            <asp:Parameter Name="Administratori" Type="Boolean" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Emri" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter DbType="Date" Name="Datelindja" />
            <asp:Parameter Name="Fjalkalimi" Type="String" />
            <asp:Parameter Name="Administratori" Type="Boolean" />
            <asp:Parameter Name="original_Id_User" Type="Int32" />
            <asp:Parameter Name="original_Emri" Type="String" />
            <asp:Parameter Name="original_Email" Type="String" />
            <asp:Parameter DbType="Date" Name="original_Datelindja" />
            <asp:Parameter Name="original_Fjalkalimi" Type="String" />
            <asp:Parameter Name="original_Administratori" Type="Boolean" />
        </UpdateParameters>
    </asp:SqlDataSource>
    
</asp:Content>

